# Use Node.js image
FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

# Add host flag to make Vite accessible from outside the container
CMD ["npm", "run", "dev", "--", "--host"]