version: '3.8'

services:
  frontend:
    image: ahmedamira22/mern-frontend:latest
    container_name: front
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:4000

  backend:
    image: ahmedamira22/mern-backend:latest  # Changed to use image
    container_name: back
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/crud?authSource=admin
      - PORT=4000
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=crud
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    name: mongo-data