# Use Node.js base image
FROM node:lts-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./

RUN npm install

# Copy the backend source code
COPY . .

# Expose the backend port
EXPOSE 9000

# Start the backend server
CMD ["npm", "start"]
