apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-app    # Added labels at metadata level
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app   # Updated to match the new label
  template:
    metadata:
      labels:
        app: backend-app  # Updated to match the new label
    spec:
      containers:
      - name: backend    # Consistent container naming
        image: ahmedamira22/mern-backend:latest
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: app-configmap