apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
        - name: back
          image: ahmedamira22/mern-backend:latest
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: app-configmap