apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: mern-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30006
  type: NodePort