# Default values for frontend chart

replicaCount: 3

image:
  repository: ahmedamira22/mern-frontend
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 80
  targetPort: 5173
  nodePort: 30006

containerPort: 5173

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

configMap:
  name: app-configmap

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Labels for the deployment and pods
labels:
  app: mern-client

# Readiness probe
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  
# Liveness probe
livenessProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3